// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArKT0c2uN1wqtzdYhm975jMCxSIU3FGYg',
    appId: '1:829478655857:android:cb47a8c923b7b0435dc8d0',
    messagingSenderId: '829478655857',
    projectId: 'bepractical18-7da02',
    storageBucket: 'bepractical18-7da02.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvsIOJKmtNxxQQroPRKn2B_BWRJVD_ils',
    appId: '1:829478655857:ios:4b9bbd593fd215755dc8d0',
    messagingSenderId: '829478655857',
    projectId: 'bepractical18-7da02',
    storageBucket: 'bepractical18-7da02.firebasestorage.app',
    androidClientId: '829478655857-vvgdj728gh1fqg2ddkqjn6dla5on4jh6.apps.googleusercontent.com',
    iosClientId: '829478655857-g9nqppath2d91ioaeaci9d3ac0vchtcr.apps.googleusercontent.com',
    iosBundleId: 'com.bepractical.bePractical18',
  );
}
